-- Close the remaining mutation bypasses after the planning and workforce
-- command APIs have been made transactional.

-- PostgreSQL removes the parent shift from the deleting transaction's visible
-- rows before the FK cascade reaches shift_assignments. The content guard must
-- still be able to resolve the schedule while deleting children, so delete
-- them explicitly from a parent BEFORE trigger.
create or replace function public.delete_shift_assignments_before_parent()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.shift_assignments assignment
  where assignment.planning_shift_id = old.id;

  return old;
end;
$$;

revoke all on function public.delete_shift_assignments_before_parent()
from public, anon, authenticated;

drop trigger if exists planning_shifts_delete_assignments_before_parent
on public.planning_shifts;

create trigger planning_shifts_delete_assignments_before_parent
before delete on public.planning_shifts
for each row execute function public.delete_shift_assignments_before_parent();

-- The API now always supplies expected_lock_version. Keeping the historical
-- overloads executable would let a caller bypass optimistic concurrency by
-- invoking PostgREST directly.
revoke all on function public.create_planning_shift(
  uuid, uuid, timestamptz, timestamptz, integer, uuid, uuid, text
) from public, anon, authenticated;
revoke all on function public.move_planning_assignment(
  uuid, uuid, date, uuid
) from public, anon, authenticated;
revoke all on function public.update_planning_assignment(
  uuid, uuid, uuid, uuid, uuid, timestamptz, timestamptz, integer, text
) from public, anon, authenticated;
revoke all on function public.delete_planning_assignment(uuid, uuid)
from public, anon, authenticated;
revoke all on function public.publish_schedule_version(uuid, text)
from public, anon, authenticated;
revoke all on function public.update_port_call_timing(
  uuid, timestamptz, timestamptz, public.port_call_status, text, text
) from public, anon, authenticated;
revoke all on function public.update_port_call_timing(
  uuid,
  timestamptz,
  timestamptz,
  public.port_call_status,
  text,
  text,
  bigint,
  text,
  timestamptz
) from public, anon, authenticated;
revoke all on function public.update_port_call_timing(
  uuid,
  timestamptz,
  timestamptz,
  public.port_call_status,
  text,
  text,
  bigint,
  text,
  timestamptz,
  bigint
) from public, anon, authenticated;
grant execute on function public.update_port_call_timing(
  uuid,
  timestamptz,
  timestamptz,
  public.port_call_status,
  text,
  text,
  bigint,
  text,
  timestamptz,
  bigint
) to service_role;

-- Interactive corrections also require the monotonic timing CAS. The legacy
-- source-revision-only overload is intentionally unavailable through REST.
revoke all on function public.override_port_call_timing(
  uuid,
  timestamptz,
  timestamptz,
  public.port_call_status,
  text,
  text,
  text,
  text,
  timestamptz
) from public, anon, authenticated;
revoke all on function public.override_port_call_timing(
  uuid,
  timestamptz,
  timestamptz,
  public.port_call_status,
  text,
  text,
  text,
  bigint,
  text,
  timestamptz
) from public, anon, authenticated;
grant execute on function public.override_port_call_timing(
  uuid,
  timestamptz,
  timestamptz,
  public.port_call_status,
  text,
  text,
  text,
  bigint,
  text,
  timestamptz
) to authenticated;

-- Rejection is coordinated across every weekly scenario generated by one
-- disruption, just like approval/publication. Candidate drafts remain in the
-- immutable history but can no longer become the current working schedule.
create or replace function public.reject_replanning_scenario(
  target_scenario_id uuid,
  rejection_reason text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_scenario public.replanning_scenarios;
  rejected_count integer;
begin
  select scenario.*
  into target_scenario
  from public.replanning_scenarios scenario
  where scenario.id = target_scenario_id
  for update;

  if target_scenario.id is null then
    raise exception 'Replanning scenario not found';
  end if;

  if target_scenario.status not in ('draft', 'simulated', 'approved') then
    raise exception 'Only a pending replanning scenario can be rejected';
  end if;

  if not public.has_role(
    target_scenario.organization_id,
    target_scenario.site_id,
    array['platform_admin', 'planning_admin', 'approver']::public.app_role[]
  ) then
    raise exception 'Insufficient permissions';
  end if;

  if rejection_reason is null
    or char_length(pg_catalog.btrim(rejection_reason)) not between 3 and 500 then
    raise exception 'A valid rejection reason is required';
  end if;

  perform 1
  from public.replanning_scenarios scenario
  where scenario.disruption_event_id = target_scenario.disruption_event_id
    and scenario.status in ('draft', 'simulated', 'approved')
  order by scenario.base_schedule_version_id, scenario.id
  for update;

  update public.schedule_versions candidate
  set superseded_at = coalesce(candidate.superseded_at, clock_timestamp()),
      change_reason = left(
        concat_ws(E'\n', candidate.change_reason, pg_catalog.btrim(rejection_reason)),
        500
      ),
      updated_at = now()
  where candidate.id in (
      select scenario.candidate_schedule_version_id
      from public.replanning_scenarios scenario
      where scenario.disruption_event_id = target_scenario.disruption_event_id
        and scenario.status in ('draft', 'simulated', 'approved')
        and scenario.candidate_schedule_version_id is not null
    )
    and candidate.status in ('draft', 'validated')
    and candidate.superseded_at is null;

  update public.replanning_scenarios scenario
  set status = 'rejected',
      summary = left(
        concat_ws(E'\n', scenario.summary, pg_catalog.btrim(rejection_reason)),
        1000
      ),
      updated_at = now()
  where scenario.disruption_event_id = target_scenario.disruption_event_id
    and scenario.status in ('draft', 'simulated', 'approved');

  get diagnostics rejected_count = row_count;

  return jsonb_build_object(
    'scenarioId', target_scenario.id,
    'disruptionEventId', target_scenario.disruption_event_id,
    'rejectedCount', rejected_count,
    'coordinated', rejected_count > 1
  );
end;
$$;

revoke all on function public.reject_replanning_scenario(uuid, text)
from public, anon, authenticated;
grant execute on function public.reject_replanning_scenario(uuid, text)
to authenticated;

-- Group targets are site-scoped. Prevent a membership from silently applying
-- another site's working rules to an agent.
do $$
begin
  if exists (
    select 1
    from public.agent_group_memberships membership
    join public.agents agent on agent.id = membership.agent_id
    join public.agent_groups agent_group on agent_group.id = membership.group_id
    where membership.organization_id <> agent.organization_id
      or membership.organization_id <> agent_group.organization_id
      or (
        agent_group.site_id is not null
        and agent_group.site_id <> agent.primary_site_id
      )
  ) then
    raise exception 'Existing agent group memberships cross organization or site boundaries'
      using errcode = 'P2002';
  end if;
end;
$$;

create or replace function public.enforce_agent_group_membership_site()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_agent public.agents;
  target_group public.agent_groups;
begin
  select agent.* into target_agent
  from public.agents agent
  where agent.id = new.agent_id;

  select agent_group.* into target_group
  from public.agent_groups agent_group
  where agent_group.id = new.group_id;

  if target_agent.id is null or target_group.id is null
    or new.organization_id <> target_agent.organization_id
    or new.organization_id <> target_group.organization_id
    or (
      target_group.site_id is not null
      and target_group.site_id <> target_agent.primary_site_id
    ) then
    raise exception 'Agent and group must belong to the same organization and site'
      using errcode = 'P2002';
  end if;

  return new;
end;
$$;

revoke all on function public.enforce_agent_group_membership_site()
from public, anon, authenticated;

drop trigger if exists agent_group_memberships_site_guard
on public.agent_group_memberships;
create trigger agent_group_memberships_site_guard
before insert or update of organization_id, group_id, agent_id
on public.agent_group_memberships
for each row execute function public.enforce_agent_group_membership_site();

-- Replanning notifications are produced by the reliable outbox only. The
-- historical trigger used to create a second pending notification directly.
create or replace function public.finalize_published_replanning()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  applied_scenario public.replanning_scenarios;
begin
  if new.status <> 'published' or old.status = 'published' then
    return new;
  end if;

  for applied_scenario in
    update public.replanning_scenarios
    set status = 'applied',
        applied_at = now(),
        updated_at = now()
    where candidate_schedule_version_id = new.id
      and status = 'approved'
    returning *
  loop
    insert into public.outbox_events (
      organization_id,
      site_id,
      topic,
      aggregate_type,
      aggregate_id,
      payload,
      idempotency_key
    ) values (
      applied_scenario.organization_id,
      applied_scenario.site_id,
      'planning.replanning.applied',
      'replanning_scenario',
      applied_scenario.id,
      jsonb_build_object(
        'scenarioId', applied_scenario.id,
        'scenarioIds', jsonb_build_array(applied_scenario.id),
        'scheduleVersionId', new.id,
        'appliedAt', now()
      ),
      'replanning-applied-' || applied_scenario.id::text
    )
    on conflict (organization_id, idempotency_key) do nothing;
  end loop;

  return new;
end;
$$;

revoke all on function public.finalize_published_replanning()
from public, anon, authenticated;

-- Existing rows produced by the former synchronous trigger are legitimate
-- durable in-app messages. Normalize them as delivered so the outbox's legacy
-- idempotency key resolves to the same single notification.
update public.agent_notifications notification
set status = 'sent',
    sent_at = coalesce(notification.sent_at, notification.created_at),
    updated_at = now()
where notification.idempotency_key like 'replanning-applied-%-agent-%'
  and notification.status = 'pending'
  and notification.sent_at is null;

-- Ending a membership is a business command: it validates scope and dates and
-- does not expose arbitrary UPDATE access to the temporal history table.
create or replace function public.end_agent_group_membership(
  target_group_id uuid,
  target_membership_id uuid,
  target_organization_id uuid,
  new_effective_until date
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_membership public.agent_group_memberships;
  target_agent public.agents;
begin
  select membership.*
  into target_membership
  from public.agent_group_memberships membership
  where membership.id = target_membership_id
    and membership.group_id = target_group_id
    and membership.organization_id = target_organization_id
  for update;

  if target_membership.id is null then
    raise exception 'Rattachement introuvable'
      using errcode = 'P2002';
  end if;

  target_agent := public.assert_workforce_agent_access(
    target_membership.agent_id,
    array['platform_admin', 'planning_admin', 'planner', 'hr']::public.app_role[]
  );

  if target_agent.organization_id <> target_organization_id then
    raise exception 'Organisation incohérente pour ce rattachement'
      using errcode = 'P2002';
  end if;

  if new_effective_until is null
    or new_effective_until < target_membership.effective_from then
    raise exception 'La fin du rattachement doit suivre son début'
      using errcode = 'P2001';
  end if;

  update public.agent_group_memberships membership
  set effective_until = case
    when membership.effective_until is null then new_effective_until
    else least(membership.effective_until, new_effective_until)
  end
  where membership.id = target_membership_id
  returning * into target_membership;

  return to_jsonb(target_membership);
end;
$$;

revoke all on function public.end_agent_group_membership(
  uuid, uuid, uuid, date
) from public, anon, authenticated;
grant execute on function public.end_agent_group_membership(
  uuid, uuid, uuid, date
) to authenticated;

-- All changes to dated HR facts must go through the commands introduced in
-- migration 032. Reads remain protected by RLS and SELECT grants.
revoke insert, update, delete on table
  public.agent_contract_versions,
  public.agent_group_memberships,
  public.agent_skills,
  public.agent_position_preferences,
  public.agent_position_restrictions
from authenticated;
